"""Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

class Solution:

    UPPER_BOUND = 4000000

    def fib(self, n):
        if (n == 0): return 0
        a = 0
        b = 1
        e = 0
        for _ in range(2, n):
            c = a + b
            if (c > self.UPPER_BOUND):
                break
            if (c % 2) == 0:
                e += c
            a = b
            b = c
        return e

if __name__ == "__main__":
    s = Solution()
    print(s.fib(50))